package api

import (
	"net/http"
	"sort"
	"strings"
)

// OpenAPI version + document metadata. Bump apiInfoVersion when the
// API surface changes in a backward-incompatible way; minor changes
// (a new endpoint, a new optional query param) bump the version's
// minor digit.
const (
	openAPIVersion = "3.0.3"
	apiInfoTitle   = "KubeAtlas API"
	apiInfoVersion = "v1alpha1"
	apiInfoLicense = "Apache-2.0"
	apiInfoLicURL  = "https://www.apache.org/licenses/LICENSE-2.0"
	apiInfoSummary = "Kubernetes resource dependency graph"
	apiInfoContact = "https://github.com/lithastra/kubeatlas"
)

// handleOpenAPI serves the spec at /api/v1alpha1/openapi.json.
func (s *Server) handleOpenAPI(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, s.openAPISpec())
}

// openAPISpec assembles the full document. The `paths` section is
// generated by walking Routes(); `components.schemas` is hand-written
// because the response schemas don't change with route additions.
func (s *Server) openAPISpec() map[string]any {
	return map[string]any{
		"openapi": openAPIVersion,
		"info": map[string]any{
			"title":   apiInfoTitle,
			"version": apiInfoVersion,
			"summary": apiInfoSummary,
			"license": map[string]any{
				"name": apiInfoLicense,
				"url":  apiInfoLicURL,
			},
			"contact": map[string]any{
				"url": apiInfoContact,
			},
		},
		"paths":      s.openAPIPaths(),
		"components": openAPIComponents(),
	}
}

// openAPIPaths walks the route table and builds an OpenAPI paths
// object. Routes are grouped by Pattern (a single path may serve
// multiple methods, though Phase 1 only uses GET).
func (s *Server) openAPIPaths() map[string]any {
	paths := map[string]any{}
	for _, r := range s.Routes() {
		entry, ok := paths[r.Pattern].(map[string]any)
		if !ok {
			entry = map[string]any{}
			paths[r.Pattern] = entry
		}
		entry[strings.ToLower(r.Method)] = openAPIOperation(r)
	}
	return paths
}

// openAPIOperation renders one Operation object for a route.
func openAPIOperation(r RouteInfo) map[string]any {
	op := map[string]any{
		"summary":     r.Summary,
		"description": r.Description,
		"operationId": operationID(r),
		"responses":   openAPIResponses(r),
	}
	params := openAPIParams(r)
	if len(params) > 0 {
		op["parameters"] = params
	}
	return op
}

// openAPIParams converts the route's path + query params into the
// OpenAPI parameters list, deterministic-ordered.
func openAPIParams(r RouteInfo) []map[string]any {
	out := make([]map[string]any, 0, len(r.PathParams)+len(r.QueryParams))
	for _, p := range r.PathParams {
		out = append(out, openAPIParam(p, "path"))
	}
	for _, p := range r.QueryParams {
		out = append(out, openAPIParam(p, "query"))
	}
	return out
}

func openAPIParam(p ParamSpec, in string) map[string]any {
	schema := map[string]any{"type": p.Type}
	if len(p.Enum) > 0 {
		// Convert []string to []any so json.Marshal emits the JSON
		// array verbatim.
		enum := make([]any, 0, len(p.Enum))
		for _, v := range p.Enum {
			enum = append(enum, v)
		}
		schema["enum"] = enum
	}
	out := map[string]any{
		"name":     p.Name,
		"in":       in,
		"required": p.Required || in == "path", // path params are always required
		"schema":   schema,
	}
	if p.Description != "" {
		out["description"] = p.Description
	}
	return out
}

// openAPIResponses renders the responses map for a route. Every route
// declares its 200 success; common error codes are referenced via
// components/responses.
func openAPIResponses(r RouteInfo) map[string]any {
	contentType := r.Response.ContentType
	if contentType == "" {
		contentType = "application/json"
	}
	successCode := "200"
	if r.Pattern == "/api/v1alpha1/watch" {
		successCode = "101" // WebSocket upgrade
	}
	successResp := map[string]any{
		"description": r.Response.Description,
	}
	if r.Response.SchemaRef != "" {
		successResp["content"] = map[string]any{
			contentType: map[string]any{
				"schema": map[string]any{
					"$ref": "#/components/schemas/" + r.Response.SchemaRef,
				},
			},
		}
	}
	resps := map[string]any{
		successCode: successResp,
	}
	// /readyz can return 503 when the informer is still syncing.
	if r.Pattern == "/readyz" {
		resps["503"] = map[string]any{
			"description": "Service not ready (informer cache still syncing)",
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": map[string]any{"$ref": "#/components/schemas/HealthResponse"},
				},
			},
		}
	}
	// All v1alpha1 endpoints can return the standard error envelopes.
	if strings.HasPrefix(r.Pattern, "/api/v1alpha1/") && r.Pattern != "/api/v1alpha1/watch" {
		resps["400"] = errorRef("Invalid request (missing or malformed parameters)")
		resps["404"] = errorRef("Resource not found")
		resps["500"] = errorRef("Internal server error")
	}
	return resps
}

func errorRef(desc string) map[string]any {
	return map[string]any{
		"description": desc,
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/ErrorResponse"},
			},
		},
	}
}

// operationID builds a stable identifier for a route, derived from
// method + pattern. e.g. "get_api_v1alpha1_graph",
// "get_api_v1alpha1_resources_namespace_kind_name_incoming".
func operationID(r RouteInfo) string {
	clean := strings.NewReplacer("/", "_", "{", "", "}", "", ".", "_").Replace(r.Pattern)
	clean = strings.Trim(clean, "_")
	return strings.ToLower(r.Method) + "_" + clean
}

// openAPIComponents returns the components/schemas section. These are
// hand-written: response shapes don't change when routes do, and
// regenerating them from Go reflection would either drag in another
// dependency or write less-readable output.
func openAPIComponents() map[string]any {
	return map[string]any{
		"schemas": map[string]any{
			"HealthResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"status": map[string]any{"type": "string", "example": "ok"},
					"reason": map[string]any{"type": "string"},
				},
				"required": []any{"status"},
			},
			"ErrorResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"error":      map[string]any{"type": "string", "description": "Human-readable error message."},
					"code":       map[string]any{"type": "string", "enum": []any{"not_found", "invalid_argument", "internal"}},
					"request_id": map[string]any{"type": "string", "description": "Optional correlation id."},
				},
				"required": []any{"error", "code"},
			},
			"OwnerRef": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"kind": map[string]any{"type": "string"},
					"name": map[string]any{"type": "string"},
					"uid":  map[string]any{"type": "string"},
				},
				"required": []any{"kind", "name", "uid"},
			},
			"Resource": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"kind":            map[string]any{"type": "string"},
					"name":            map[string]any{"type": "string"},
					"namespace":       map[string]any{"type": "string"},
					"labels":          map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
					"groupVersion":    map[string]any{"type": "string"},
					"uid":             map[string]any{"type": "string"},
					"annotations":     map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
					"ownerReferences": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/OwnerRef"}},
					"resourceVersion": map[string]any{"type": "string"},
				},
				"required": []any{"kind", "name", "namespace"},
			},
			"Edge": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"from": map[string]any{"type": "string", "description": "Source resource id (namespace/kind/name)."},
					"to":   map[string]any{"type": "string", "description": "Target resource id."},
					"type": map[string]any{
						"type": "string",
						"enum": []any{
							"OWNS", "USES_CONFIGMAP", "USES_SECRET", "MOUNTS_VOLUME",
							"SELECTS", "USES_SERVICEACCOUNT", "ROUTES_TO", "ATTACHED_TO",
						},
					},
				},
				"required": []any{"from", "to", "type"},
			},
			"EdgeList": map[string]any{
				"type":  "array",
				"items": map[string]any{"$ref": "#/components/schemas/Edge"},
			},
			"ViewNode": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"id":               map[string]any{"type": "string"},
					"type":             map[string]any{"type": "string", "enum": []any{"aggregated", "resource"}},
					"level":            map[string]any{"type": "string", "enum": []any{"cluster", "namespace", "workload", "resource"}},
					"label":            map[string]any{"type": "string"},
					"kind":             map[string]any{"type": "string"},
					"namespace":        map[string]any{"type": "string"},
					"name":             map[string]any{"type": "string"},
					"children_count":   map[string]any{"type": "integer"},
					"children_summary": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "integer"}},
					"edge_count_in":    map[string]any{"type": "integer"},
					"edge_count_out":   map[string]any{"type": "integer"},
				},
				"required": []any{"id", "type", "edge_count_in", "edge_count_out"},
			},
			"ViewEdge": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"from":  map[string]any{"type": "string"},
					"to":    map[string]any{"type": "string"},
					"type":  map[string]any{"type": "string"},
					"count": map[string]any{"type": "integer"},
				},
				"required": []any{"from", "to", "count"},
			},
			"View": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"level":     map[string]any{"type": "string", "enum": []any{"cluster", "namespace", "workload", "resource"}},
					"nodes":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ViewNode"}},
					"edges":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ViewEdge"}},
					"truncated": map[string]any{"type": "boolean"},
				},
				"required": []any{"level", "nodes", "edges"},
			},
			"ResourceDetailResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"resource": map[string]any{"$ref": "#/components/schemas/Resource"},
					"incoming": map[string]any{"$ref": "#/components/schemas/EdgeList"},
					"outgoing": map[string]any{"$ref": "#/components/schemas/EdgeList"},
				},
				"required": []any{"resource", "incoming", "outgoing"},
			},
			"SearchResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"matches":   map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"total":     map[string]any{"type": "integer"},
					"truncated": map[string]any{"type": "boolean"},
				},
				"required": []any{"matches", "total", "truncated"},
			},
			"OpenAPI": map[string]any{
				"type":        "object",
				"description": "OpenAPI 3.0 document. Self-describing; clients should consume the spec directly rather than this schema entry.",
			},
		},
	}
}

// PathPatterns returns just the URL patterns the route table contains,
// in the order Routes() returned them. Used by the contract test.
func (s *Server) PathPatterns() []string {
	out := make([]string, 0, len(s.Routes()))
	for _, r := range s.Routes() {
		out = append(out, r.Pattern)
	}
	sort.Strings(out)
	return out
}
