package api

import (
	"net/http"
	"sort"
	"strings"
)

// OpenAPI version + document metadata. Bump apiInfoVersion when the
// API surface changes in a backward-incompatible way; minor changes
// (a new endpoint, a new optional query param) bump the version's
// minor digit.
const (
	openAPIVersion = "3.0.3"
	apiInfoTitle   = "KubeAtlas API"
	apiInfoVersion = "v1alpha1"
	apiInfoLicense = "Apache-2.0"
	apiInfoLicURL  = "https://www.apache.org/licenses/LICENSE-2.0"
	apiInfoSummary = "Kubernetes resource dependency graph"
	apiInfoContact = "https://github.com/lithastra/kubeatlas"
)

// handleOpenAPI serves the spec at /api/v{version}/openapi.json.
// The version is inferred from the request path so the same
// handler powers both /api/v1alpha1/openapi.json and
// /api/v1/openapi.json — each renders only its version's paths
// and the version-appropriate component schemas.
func (s *Server) handleOpenAPI(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, s.openAPISpecFor(apiVersionFor(r)))
}

// openAPISpecFor assembles the full document for one API version.
// The `paths` section is generated by walking Routes() and
// remapping patterns to the requested prefix; `components.schemas`
// is hand-written and version-aware (v1 carries the GA-only
// enrichment fields on ResourceDetailResponse; v1alpha1 keeps the
// frozen Phase 1 shape).
func (s *Server) openAPISpecFor(version string) map[string]any {
	return map[string]any{
		"openapi": openAPIVersion,
		"info": map[string]any{
			"title":   apiInfoTitle,
			"version": version,
			"summary": apiInfoSummary,
			"license": map[string]any{
				"name": apiInfoLicense,
				"url":  apiInfoLicURL,
			},
			"contact": map[string]any{
				"url": apiInfoContact,
			},
		},
		"paths":      s.openAPIPathsFor(version),
		"components": openAPIComponentsFor(version),
	}
}

// OpenAPISpecV1Alpha1 exposes the frozen v1alpha1 spec to
// out-of-process tooling — specifically the
// tools/api-compat-check dumper, which CI uses to detect any
// drift from the v0.1.0 baseline. Public so the tool can call
// it without copying the route-walking logic.
func (s *Server) OpenAPISpecV1Alpha1() map[string]any {
	return s.openAPISpecFor(APIVersionV1Alpha1)
}

// OpenAPISpecV1 is the GA-version twin. Same contract as
// OpenAPISpecV1Alpha1.
func (s *Server) OpenAPISpecV1() map[string]any {
	return s.openAPISpecFor(APIVersionV1)
}

// openAPIPathsFor builds the paths object for a specific API
// version. Patterns under /api/v1alpha1/... are remapped to the
// requested prefix; unversioned routes (/healthz, /readyz,
// /metrics) appear in both specs unchanged because operators
// hit those identically regardless of API version.
func (s *Server) openAPIPathsFor(version string) map[string]any {
	paths := map[string]any{}
	for _, r := range s.Routes() {
		// v1-only routes (e.g. /api/v1/federation/...) must not leak
		// into the v1alpha1 spec — that surface is frozen.
		if version == APIVersionV1Alpha1 && strings.HasPrefix(r.Pattern, apiPrefixV1) {
			continue
		}
		pattern := versionedPattern(r.Pattern, version)
		entry, ok := paths[pattern].(map[string]any)
		if !ok {
			entry = map[string]any{}
			paths[pattern] = entry
		}
		entry[strings.ToLower(r.Method)] = openAPIOperationFor(r, version)
	}
	return paths
}

// openAPIOperationFor adjusts the version-sensitive parts of an
// operation entry (currently just the response schema reference
// for ResourceDetailResponse, which carries the v1-only enrichment
// fields).
func openAPIOperationFor(r RouteInfo, version string) map[string]any {
	op := openAPIOperation(r)
	if version == APIVersionV1 && r.Response.SchemaRef == "ResourceDetailResponse" {
		// Override the success-content $ref to point at the v1
		// shape so the spec advertises the GA-only fields.
		if responses, ok := op["responses"].(map[string]any); ok {
			if okResp, ok := responses["200"].(map[string]any); ok {
				if content, ok := okResp["content"].(map[string]any); ok {
					if app, ok := content["application/json"].(map[string]any); ok {
						app["schema"] = map[string]any{
							"$ref": "#/components/schemas/ResourceDetailResponseV1",
						}
					}
				}
			}
		}
	}
	return op
}

// openAPIOperation renders one Operation object for a route.
func openAPIOperation(r RouteInfo) map[string]any {
	op := map[string]any{
		"summary":     r.Summary,
		"description": r.Description,
		"operationId": operationID(r),
		"responses":   openAPIResponses(r),
	}
	params := openAPIParams(r)
	if len(params) > 0 {
		op["parameters"] = params
	}
	return op
}

// openAPIParams converts the route's path + query params into the
// OpenAPI parameters list, deterministic-ordered.
func openAPIParams(r RouteInfo) []map[string]any {
	out := make([]map[string]any, 0, len(r.PathParams)+len(r.QueryParams))
	for _, p := range r.PathParams {
		out = append(out, openAPIParam(p, "path"))
	}
	for _, p := range r.QueryParams {
		out = append(out, openAPIParam(p, "query"))
	}
	return out
}

func openAPIParam(p ParamSpec, in string) map[string]any {
	schema := map[string]any{"type": p.Type}
	if len(p.Enum) > 0 {
		// Convert []string to []any so json.Marshal emits the JSON
		// array verbatim.
		enum := make([]any, 0, len(p.Enum))
		for _, v := range p.Enum {
			enum = append(enum, v)
		}
		schema["enum"] = enum
	}
	out := map[string]any{
		"name":     p.Name,
		"in":       in,
		"required": p.Required || in == "path", // path params are always required
		"schema":   schema,
	}
	if p.Description != "" {
		out["description"] = p.Description
	}
	return out
}

// openAPIResponses renders the responses map for a route. Every route
// declares its 200 success; common error codes are referenced via
// components/responses.
func openAPIResponses(r RouteInfo) map[string]any {
	contentType := r.Response.ContentType
	if contentType == "" {
		contentType = "application/json"
	}
	successCode := "200"
	if r.Pattern == "/api/v1alpha1/watch" {
		successCode = "101" // WebSocket upgrade
	}
	successResp := map[string]any{
		"description": r.Response.Description,
	}
	if r.Response.SchemaRef != "" {
		successResp["content"] = map[string]any{
			contentType: map[string]any{
				"schema": map[string]any{
					"$ref": "#/components/schemas/" + r.Response.SchemaRef,
				},
			},
		}
	}
	resps := map[string]any{
		successCode: successResp,
	}
	// /readyz can return 503 when the informer is still syncing.
	if r.Pattern == "/readyz" {
		resps["503"] = map[string]any{
			"description": "Service not ready (informer cache still syncing)",
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": map[string]any{"$ref": "#/components/schemas/HealthResponse"},
				},
			},
		}
	}
	// All v1alpha1 endpoints can return the standard error envelopes.
	if strings.HasPrefix(r.Pattern, "/api/v1alpha1/") && r.Pattern != "/api/v1alpha1/watch" {
		resps["400"] = errorRef("Invalid request (missing or malformed parameters)")
		resps["404"] = errorRef("Resource not found")
		resps["500"] = errorRef("Internal server error")
	}
	return resps
}

func errorRef(desc string) map[string]any {
	return map[string]any{
		"description": desc,
		"content": map[string]any{
			"application/json": map[string]any{
				"schema": map[string]any{"$ref": "#/components/schemas/ErrorResponse"},
			},
		},
	}
}

// operationID builds a stable identifier for a route, derived from
// method + pattern. e.g. "get_api_v1alpha1_graph",
// "get_api_v1alpha1_resources_namespace_kind_name_incoming".
func operationID(r RouteInfo) string {
	clean := strings.NewReplacer("/", "_", "{", "", "}", "", ".", "_").Replace(r.Pattern)
	clean = strings.Trim(clean, "_")
	return strings.ToLower(r.Method) + "_" + clean
}

// openAPIComponentsFor returns the components/schemas section
// scoped to one API version. v1 carries the GA enrichment fields
// (blastRadiusCount, isOrphan, inCycle) on a sibling
// ResourceDetailResponseV1 schema; v1alpha1 keeps the frozen
// Phase 1 shape so api-compat-check stays green forever.
func openAPIComponentsFor(version string) map[string]any {
	c := openAPIComponentsBase()
	if version == APIVersionV1 {
		schemas, ok := c["schemas"].(map[string]any)
		if !ok {
			return c
		}
		schemas["ResourceDetailResponseV1"] = map[string]any{
			"type":        "object",
			"description": "v1-only superset of ResourceDetailResponse with graph-analysis enrichment fields. v1alpha1 omits these for byte-identical compat with the Phase 1 shape.",
			"properties": map[string]any{
				"resource":         map[string]any{"$ref": "#/components/schemas/Resource"},
				"incoming":         map[string]any{"$ref": "#/components/schemas/EdgeList"},
				"outgoing":         map[string]any{"$ref": "#/components/schemas/EdgeList"},
				"blastRadiusCount": map[string]any{"type": "integer", "description": "Number of distinct resources reachable by walking incoming edges."},
				"isOrphan":         map[string]any{"type": "boolean", "description": "True when the resource is non-top-level and has zero incoming edges."},
				"inCycle":          map[string]any{"type": "boolean", "description": "True when the resource participates in a strongly connected component of size >= 2."},
			},
			"required": []any{"resource", "incoming", "outgoing", "blastRadiusCount", "isOrphan", "inCycle"},
		}
		// P4-T1 F-301 diagnose report — v1-only (Phase 4 surface).
		schemas["DiagnoseReport"] = map[string]any{
			"type":        "object",
			"description": "Body of GET /api/v1/diagnose?format=json: the scoped dependency graph plus orphan, cycle, and top blast-radius analysis. The same data renders to a self-contained HTML report.",
			"properties": map[string]any{
				"generatedAt":      map[string]any{"type": "string", "format": "date-time"},
				"kubeAtlasVersion": map[string]any{"type": "string"},
				"scope": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"namespace":     map[string]any{"type": "string"},
						"allNamespaces": map[string]any{"type": "boolean"},
					},
					"required": []any{"allNamespaces"},
				},
				"graph": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"resources": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
						"edges":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Edge"}},
					},
				},
				"orphans": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/OrphanReport"}},
				"cycles":  map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/CycleReport"}},
				"topBlastRadius": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"resource": map[string]any{"$ref": "#/components/schemas/Resource"},
							"affected": map[string]any{"type": "integer"},
						},
						"required": []any{"resource", "affected"},
					},
				},
				"resourceCount": map[string]any{"type": "integer"},
				"edgeCount":     map[string]any{"type": "integer"},
			},
			"required": []any{"generatedAt", "kubeAtlasVersion", "scope", "graph", "orphans", "cycles", "topBlastRadius", "resourceCount", "edgeCount"},
		}

		// Policy integration — v1-only (Phase 4 surface).
		schemas["PolicyConstraint"] = map[string]any{
			"type":        "object",
			"description": "One admission-policy constraint and its live violation count.",
			"properties": map[string]any{
				"name":       map[string]any{"type": "string"},
				"kind":       map[string]any{"type": "string"},
				"engine":     map[string]any{"type": "string", "enum": []any{"gatekeeper", "kyverno"}},
				"violations": map[string]any{"type": "integer"},
			},
			"required": []any{"name", "kind", "engine", "violations"},
		}
		schemas["PolicyConstraintList"] = map[string]any{
			"type":        "array",
			"description": "Body of GET /api/v1/policy/constraints: every constraint, sorted by name.",
			"items":       map[string]any{"$ref": "#/components/schemas/PolicyConstraint"},
		}
		schemas["AffectedResource"] = map[string]any{
			"type":        "object",
			"description": "A resource a constraint enforces, with its current violation status.",
			"properties": map[string]any{
				"resource": map[string]any{"$ref": "#/components/schemas/Resource"},
				"violated": map[string]any{"type": "boolean"},
				"message":  map[string]any{"type": "string"},
			},
			"required": []any{"resource", "violated"},
		}
		schemas["ConstraintAffectedResponse"] = map[string]any{
			"type":        "object",
			"description": "Body of GET /api/v1/policy/constraints/{name}/affected.",
			"properties": map[string]any{
				"constraint": map[string]any{"type": "string"},
				"resources":  map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/AffectedResource"}},
				"count":      map[string]any{"type": "integer"},
			},
			"required": []any{"constraint", "resources", "count"},
		}

		// Build + internal store info — v1-only.
		schemas["InfoResponse"] = map[string]any{
			"type":        "object",
			"description": "Body of GET /api/v1/info: server build metadata plus the internal GraphStore interface version. graphstore_version is an internal engineering version (e.g. \"v2\"), unrelated to the product release version or the v1alpha1/v1 HTTP API versions.",
			"properties": map[string]any{
				"version":            map[string]any{"type": "string"},
				"commit":             map[string]any{"type": "string"},
				"build_date":         map[string]any{"type": "string"},
				"graphstore_version": map[string]any{"type": "string"},
			},
			"required": []any{"version", "commit", "build_date", "graphstore_version"},
		}

		// Opt-in telemetry — v1-only (Phase 4 surface).
		schemas["TelemetryStatusResponse"] = map[string]any{
			"type":        "object",
			"description": "Body of GET /api/v1/telemetry/status.",
			"properties": map[string]any{
				"enabled":   map[string]any{"type": "boolean"},
				"endpoint":  map[string]any{"type": "string"},
				"last_sent": map[string]any{"type": "string", "format": "date-time"},
				"next_send": map[string]any{"type": "string", "format": "date-time"},
			},
			"required": []any{"enabled"},
		}
		schemas["TelemetryPayload"] = map[string]any{
			"type":        "object",
			"description": "The anonymous payload a telemetry report sends. No resource names, namespaces, label values, IPs, or cross-session identifiers.",
			"properties": map[string]any{
				"schema_version":        map[string]any{"type": "string"},
				"kubeatlas_version":     map[string]any{"type": "string"},
				"k8s_version":           map[string]any{"type": "string"},
				"os":                    map[string]any{"type": "string"},
				"arch":                  map[string]any{"type": "string"},
				"tier":                  map[string]any{"type": "string", "enum": []any{"memory", "postgres"}},
				"resource_bucket":       map[string]any{"type": "string", "enum": []any{"<1K", "1K-5K", "5K-10K", ">10K"}},
				"enabled_packs":         map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"cluster_count":         map[string]any{"type": "integer"},
				"platform_distribution": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "integer"}},
				"session_nonce":         map[string]any{"type": "string", "description": "Random per process start; never persisted, cannot correlate sessions."},
			},
			"required": []any{"schema_version", "kubeatlas_version", "os", "arch", "tier", "resource_bucket", "session_nonce"},
		}

		// P3-T22 federation surface — v1-only, since v1alpha1 is frozen.
		schemas["FederationClustersResponse"] = map[string]any{
			"type":        "object",
			"description": "Body of /api/v1/federation/clusters. mode='single' means multicluster is disabled on this server; mode='federated' returns the attached member-cluster names.",
			"properties": map[string]any{
				"mode":     map[string]any{"type": "string", "enum": []any{"single", "federated"}},
				"clusters": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
			},
			"required": []any{"mode", "clusters"},
		}
		schemas["FederatedNode"] = map[string]any{
			"type":        "object",
			"description": "A node in the federation view. The shape is a union: type='resource' carries Kind / Namespace / Name (raw graph resource); type='cluster' carries Label / ResourceCount / NamespaceCount / KindSummary (per-cluster summary, returned by level=cluster). Every node always carries ID and ClusterID.",
			"properties": map[string]any{
				"id":             map[string]any{"type": "string"},
				"type":           map[string]any{"type": "string", "enum": []any{"resource", "cluster"}},
				"clusterId":      map[string]any{"type": "string"},
				"kind":           map[string]any{"type": "string"},
				"namespace":      map[string]any{"type": "string"},
				"name":           map[string]any{"type": "string"},
				"label":          map[string]any{"type": "string"},
				"resourceCount":  map[string]any{"type": "integer"},
				"namespaceCount": map[string]any{"type": "integer"},
				"kindSummary": map[string]any{
					"type":                 "object",
					"additionalProperties": map[string]any{"type": "integer"},
				},
			},
			"required": []any{"id", "type", "clusterId"},
		}
		schemas["FederatedView"] = map[string]any{
			"type":        "object",
			"description": "Body of /api/v1/federation/graph. level='resource' is the default — a flat union of resources and intra-cluster edges across the named clusters. level='cluster' is the small-payload zoom — one Node per cluster with a resource count and a top-N kind summary; edges are always empty at this level. Cross-cluster edges are deferred to a follow-up release.",
			"properties": map[string]any{
				"level":    map[string]any{"type": "string", "enum": []any{"resource", "cluster"}},
				"clusters": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				"nodes":    map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/FederatedNode"}},
				"edges":    map[string]any{"$ref": "#/components/schemas/EdgeList"},
			},
			"required": []any{"level", "clusters", "nodes", "edges"},
		}
	}
	return c
}

// openAPIComponentsBase is the version-agnostic component set —
// every schema both versions share. Per-version extensions are
// applied by openAPIComponentsFor.
func openAPIComponentsBase() map[string]any {
	return map[string]any{
		"schemas": map[string]any{
			"HealthResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"status": map[string]any{"type": "string", "example": "ok"},
					"reason": map[string]any{"type": "string"},
				},
				"required": []any{"status"},
			},
			"ErrorResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"error":      map[string]any{"type": "string", "description": "Human-readable error message."},
					"code":       map[string]any{"type": "string", "enum": []any{"not_found", "invalid_argument", "internal"}},
					"request_id": map[string]any{"type": "string", "description": "Optional correlation id."},
				},
				"required": []any{"error", "code"},
			},
			"OwnerRef": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"kind": map[string]any{"type": "string"},
					"name": map[string]any{"type": "string"},
					"uid":  map[string]any{"type": "string"},
				},
				"required": []any{"kind", "name", "uid"},
			},
			"Resource": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"kind":            map[string]any{"type": "string"},
					"name":            map[string]any{"type": "string"},
					"namespace":       map[string]any{"type": "string"},
					"labels":          map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
					"groupVersion":    map[string]any{"type": "string"},
					"uid":             map[string]any{"type": "string"},
					"annotations":     map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}},
					"ownerReferences": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/OwnerRef"}},
					"resourceVersion": map[string]any{"type": "string"},
				},
				"required": []any{"kind", "name", "namespace"},
			},
			"Edge": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"from": map[string]any{"type": "string", "description": "Source resource id (namespace/kind/name)."},
					"to":   map[string]any{"type": "string", "description": "Target resource id."},
					"type": map[string]any{
						"type": "string",
						"enum": []any{
							"OWNS", "USES_CONFIGMAP", "USES_SECRET", "MOUNTS_VOLUME",
							"SELECTS", "USES_SERVICEACCOUNT", "ROUTES_TO", "ATTACHED_TO",
							"ENFORCES",
						},
					},
					"attributes": map[string]any{
						"type":                 "object",
						"additionalProperties": map[string]any{"type": "string"},
						"description":          "Optional edge metadata. ENFORCES edges carry policy violation status (violated, violation_message); omitted when empty.",
					},
				},
				"required": []any{"from", "to", "type"},
			},
			"EdgeList": map[string]any{
				"type":  "array",
				"items": map[string]any{"$ref": "#/components/schemas/Edge"},
			},
			"ViewNode": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"id":               map[string]any{"type": "string"},
					"type":             map[string]any{"type": "string", "enum": []any{"aggregated", "resource"}},
					"level":            map[string]any{"type": "string", "enum": []any{"cluster", "namespace", "workload", "resource"}},
					"label":            map[string]any{"type": "string"},
					"kind":             map[string]any{"type": "string"},
					"namespace":        map[string]any{"type": "string"},
					"name":             map[string]any{"type": "string"},
					"children_count":   map[string]any{"type": "integer"},
					"children_summary": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "integer"}},
					"edge_count_in":    map[string]any{"type": "integer"},
					"edge_count_out":   map[string]any{"type": "integer"},
				},
				"required": []any{"id", "type", "edge_count_in", "edge_count_out"},
			},
			"ViewEdge": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"from":  map[string]any{"type": "string"},
					"to":    map[string]any{"type": "string"},
					"type":  map[string]any{"type": "string"},
					"count": map[string]any{"type": "integer"},
				},
				"required": []any{"from", "to", "count"},
			},
			"View": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"level":     map[string]any{"type": "string", "enum": []any{"cluster", "namespace", "workload", "resource"}},
					"nodes":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ViewNode"}},
					"edges":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/ViewEdge"}},
					"truncated": map[string]any{"type": "boolean"},
				},
				"required": []any{"level", "nodes", "edges"},
			},
			"ResourceDetailResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"resource": map[string]any{"$ref": "#/components/schemas/Resource"},
					"incoming": map[string]any{"$ref": "#/components/schemas/EdgeList"},
					"outgoing": map[string]any{"$ref": "#/components/schemas/EdgeList"},
				},
				"required": []any{"resource", "incoming", "outgoing"},
			},
			"SearchResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"matches":   map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"total":     map[string]any{"type": "integer"},
					"truncated": map[string]any{"type": "boolean"},
					"warning":   map[string]any{"type": "string", "description": "Present when search ran as an unindexed Tier 1 linear scan."},
				},
				"required": []any{"matches", "total", "truncated"},
			},
			"LabelValue": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"value": map[string]any{"type": "string"},
					"count": map[string]any{"type": "integer"},
				},
				"required": []any{"value", "count"},
			},
			"LabelStat": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"key":           map[string]any{"type": "string"},
					"resourceCount": map[string]any{"type": "integer"},
					"valueCount":    map[string]any{"type": "integer", "description": "Distinct values seen; exceeds len(values) when the value list was capped."},
					"values":        map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/LabelValue"}},
				},
				"required": []any{"key", "resourceCount", "valueCount"},
			},
			"LabelsResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"labels": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/LabelStat"}},
					"count":  map[string]any{"type": "integer"},
				},
				"required": []any{"labels", "count"},
			},
			"OpenAPI": map[string]any{
				"type":        "object",
				"description": "OpenAPI 3.0 document. Self-describing; clients should consume the spec directly rather than this schema entry.",
			},
			"RBACSubjectRef": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"kind":      map[string]any{"type": "string"},
					"namespace": map[string]any{"type": "string"},
					"name":      map[string]any{"type": "string"},
				},
				"required": []any{"kind", "name"},
			},
			"RBACRule": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"apiGroups":     map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					"resources":     map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					"resourceNames": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					"verbs":         map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				},
			},
			"RBACBinding": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"binding":  map[string]any{"$ref": "#/components/schemas/RBACSubjectRef"},
					"role":     map[string]any{"$ref": "#/components/schemas/RBACSubjectRef"},
					"rules":    map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/RBACRule"}},
					"subjects": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/RBACSubjectRef"}},
				},
				"required": []any{"binding"},
			},
			"RBACPermissions": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"subject":  map[string]any{"$ref": "#/components/schemas/RBACSubjectRef"},
					"bindings": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/RBACBinding"}},
				},
				"required": []any{"subject", "bindings"},
			},
			"RBACSubjects": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"role":     map[string]any{"$ref": "#/components/schemas/RBACSubjectRef"},
					"bindings": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/RBACBinding"}},
				},
				"required": []any{"role", "bindings"},
			},
			"CycleReport": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"members": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"category": map[string]any{
						"type":        "string",
						"enum":        []any{"bootstrap-cert", "intentional", "unknown"},
						"description": "Cycle shape classification. bootstrap-cert: 2-cycle where one member is a Secret owned by the other (cert-manager / CNPG / kyverno bootstrap pattern, benign). intentional: any member carries the kubeatlas.io/intentional-cycle=true annotation. unknown: every other cycle — verifiers and the GitHub Action treat this as actionable. Clients should treat unrecognised values as 'unknown'.",
					},
				},
				"required": []any{"members", "category"},
			},
			"CyclesResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"cycles": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/CycleReport"}},
					"count":  map[string]any{"type": "integer"},
				},
				"required": []any{"cycles", "count"},
			},
			"OrphanReport": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"resource": map[string]any{"$ref": "#/components/schemas/Resource"},
					"reason":   map[string]any{"type": "string", "enum": []any{"orphan", "standalone_pod"}},
				},
				"required": []any{"resource", "reason"},
			},
			"OrphansResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"reports": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/OrphanReport"}},
					"count":   map[string]any{"type": "integer"},
				},
				"required": []any{"reports", "count"},
			},
			"BlastRadiusResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"source":   map[string]any{"$ref": "#/components/schemas/Resource"},
					"affected": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"count":    map[string]any{"type": "integer"},
					"maxDepth": map[string]any{"type": "integer"},
				},
				"required": []any{"source", "affected", "count", "maxDepth"},
			},
			"SnapshotMeta": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"id":            map[string]any{"type": "integer"},
					"ts":            map[string]any{"type": "string", "format": "date-time"},
					"clusterId":     map[string]any{"type": "string"},
					"resourceCount": map[string]any{"type": "integer"},
					"edgeCount":     map[string]any{"type": "integer"},
					"durationMs":    map[string]any{"type": "integer"},
					"trigger":       map[string]any{"type": "string", "enum": []any{"periodic", "manual", "startup"}},
				},
				"required": []any{"id", "ts", "resourceCount", "edgeCount", "durationMs", "trigger"},
			},
			"SnapshotListResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"snapshots": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/SnapshotMeta"}},
					"count":     map[string]any{"type": "integer"},
				},
				"required": []any{"snapshots", "count"},
			},
			"DiffEntry": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"namespace": map[string]any{"type": "string"},
					"kind":      map[string]any{"type": "string"},
					"name":      map[string]any{"type": "string"},
					"uid":       map[string]any{"type": "string"},
					"eventType": map[string]any{"type": "string", "enum": []any{"add", "update", "delete"}},
					"ts":        map[string]any{"type": "string", "format": "date-time"},
				},
				"required": []any{"namespace", "kind", "name", "eventType", "ts"},
			},
			"DiffResult": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"from":     map[string]any{"type": "string", "format": "date-time"},
					"to":       map[string]any{"type": "string", "format": "date-time"},
					"added":    map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/DiffEntry"}},
					"removed":  map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/DiffEntry"}},
					"modified": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/DiffEntry"}},
				},
				"required": []any{"from", "to", "added", "removed", "modified"},
			},
			"SnapshotTriggerResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"trigger":       map[string]any{"type": "string", "enum": []any{"periodic", "manual"}},
					"resourceCount": map[string]any{"type": "integer"},
					"edgeCount":     map[string]any{"type": "integer"},
					"durationMs":    map[string]any{"type": "integer"},
				},
				"required": []any{"trigger", "resourceCount", "edgeCount", "durationMs"},
			},
			"NetworkPolicySelectedResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"networkPolicy": map[string]any{"$ref": "#/components/schemas/Resource"},
					"selected":      map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"count":         map[string]any{"type": "integer"},
				},
				"required": []any{"networkPolicy", "selected", "count"},
			},
			"NetworkPolicyAllowGraphResponse": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"networkPolicy": map[string]any{"$ref": "#/components/schemas/Resource"},
					"allowFrom":     map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
					"allowTo":       map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/Resource"}},
				},
				"required": []any{"networkPolicy", "allowFrom", "allowTo"},
			},
		},
	}
}

// PathPatterns returns just the URL patterns the route table contains,
// in the order Routes() returned them. Used by the contract test.
func (s *Server) PathPatterns() []string {
	out := make([]string, 0, len(s.Routes()))
	for _, r := range s.Routes() {
		out = append(out, r.Pattern)
	}
	sort.Strings(out)
	return out
}
